### ISSUE TITLE
[Idea] Activity bar

### ISSUE THREAD

**Issue by shermp** [NiLuJe/FBInk#12] opened 2018-09-14 00:06 UTC
Quick! Hide! I have another one...

So, FBInk has a progress bar. But sometimes we have to wait for an indeterminate amount of time for a task to complete. Wouldn't it be great if we had a nice scrolling activity bar to reassure the user that, no, we haven't crashed?

The idea would be to define a fixed range of positions that the dev can set the 'scroll bar/widget' to, and that way the dev can decide on their scrolling pattern and frequency. Sure, such an idea is not going to result in smooth scrolling, but it would be effective enough.

Thoughts?

Right, I'll see myself out now. :)

**Comment by NiLuJe** [comment] 2018-09-14 05:27
It's definitely something useful to have ;).

I went with a simple spinner in a backgrounder subshell in KOReader (https://github.com/koreader/koreader/blob/master/platform/common/spinning_zsync), but I guess something of the sort could be backed in...

It'd of course be blocking ;).

In terms of looks, does what you had in mind resembles the horizontal bar example in that script?

**Comment by NiLuJe** [comment] 2018-09-14 06:01
Basically something resembling an infinite progress bar, or indeterminate, or striped, right?

Either filling and emptying, or striped (that's going to be tricky, maybe just a scrolling thumb)?

**Comment by NiLuJe** [comment] 2018-09-14 06:07
If I understood your second paragraph properly, you were thinking of a scrolling thumb with a fixed number of possible steps (say, 10), on a non-blocking call, so you can "move" the thumb on your own terms instead of relying on a fixed scrolling running in the background, that you'd have to interrupt when processing finally ends.

**Comment by shermp** [comment] 2018-09-14 06:34
Yep, that's what I was thinking about.

**Comment by NiLuJe** [comment] 2018-09-16 21:00
Okay, initial implementation is in ;).

Mainly because that was originally how I thought about it, I *did* sneak in a "loop forever" behavior...

The thumb is 10% of the width, and moves in 5% increment, so that makes 19 steps.

The function takes 20 possible values as valid: 1-19 for those steps, and 0, which will loop forever, cycling between each step every 500ms.
Killing that is left to the caller, however that ends up being used (probably in a detached thread in C, or in whatever the language can do to run stuff in the bg, coroutines, backgrounding, whatever ;)).

**Comment by NiLuJe** [comment] 2018-09-16 21:12
I'm open to suggestions on how to make it look prettier ;).

**Comment by shermp** [comment] 2018-09-16 21:17
Sounds good! Look forward to testing it.

On a side note, I may have gotten a little side-tracked yesterday and somehow ended up making an onscreen keyboard (and painting it with FBInk). Oops :D

**Comment by NiLuJe** [comment] 2018-09-16 22:43
Random braindump: I *may* move the "infinite loop" thingy out of the API and into the CLI client only, because that feels slightly crazy as it is... ;).

**Comment by NiLuJe** [comment] 2018-09-18 00:42
Quite probably, given that I can't seem to reproduce it with LTO disabled ;).

**Comment by NiLuJe** [comment] 2018-09-19 16:06
Landed in v1.7.0 ;).

**Closed by NiLuJe** 2018-09-19 16:06 UTC
